name: SolarPanel
version: ''

main: org.test.solarPanel.SolarPanel
api-version: '1.13'
load: POSTWORLD

commands:
  fly:
    description:
      ᴀᴛᴛɪᴠᴀ ɪʟ ᴠᴏʟᴏ (ꜱᴏʟᴏ ᴘᴇʀ ꜱᴛᴀꜰꜰ)
    usage:
      /<command>
    aliases:
      - f
    permission: solarpanel.fly

  gmc:
    description:
      ᴀᴛᴛɪᴠᴀ ᴄʀᴇᴀᴛɪᴠᴀ (ꜱᴏʟᴏ ᴘᴇʀ ꜱᴛᴀꜰꜰ)
    usage:
      /<command>
    permission: solarpanel.gmc

  gms:
    description:
      ᴀᴛᴛɪᴠᴀ ꜱᴜʀᴠɪᴠᴀʟ (ꜱᴏʟᴏ ᴘᴇʀ ꜱᴛᴀꜰꜰ)
    usage:
      /<command>
    permission: solarpanel.gms
  tp:
    description:
      ᴜᴛɪʟɪᴢᴢᴀ ɪʟ ᴛᴇʟᴇᴛʀᴀꜱᴘᴏʀᴛᴏ (ꜱᴏʟᴏ ᴘᴇʀ ꜱᴛᴀꜰꜰ)
  pannello:
    description:
      apri la gui
    aliases:
      - p
      - panel
